"""empty message

Revision ID: 18b496cad2ca
Revises: a262f2815496
Create Date: 2018-06-21 13:24:17.883261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b496cad2ca'
down_revision = 'a262f2815496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('iccid', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'iccid')
    # ### end Alembic commands ###
