"""empty message

Revision ID: a262f2815496
Revises: 
Create Date: 2018-06-18 23:07:20.081475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a262f2815496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('sim_sid', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('extension', sa.Integer(), nullable=False),
    sa.Column('sent_welcome_message', sa.Boolean(), server_default='F', nullable=False),
    sa.Column('onboarded', sa.Boolean(), server_default='F', nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], name='sub_net_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber')
    op.drop_table('network')
    # ### end Alembic commands ###
